name: ZAP Full Scan

on:
  push:
    branches:
      - develop
      - feat/integrate-zap

jobs:
  zap-scan:
    name: OWASP ZAP Full Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run baseline scan on the deployed URL
        run: |
          docker run --name zap -v ${{ github.workspace }}/zap:/zap-config -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t ${{ secrets.DEPLOY_URL }} -c /zap-config/zap.conf -z "-config failOnError=true -config alertThreshold=High"

      - name: Clean up ZAP container
        run: docker stop zap && docker rm zap
